name: Rust

on: [push]

jobs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        default: true

    - name: rustup component add
      run: rustup component add clippy

    - name: Lint
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --verbose --all --all-targets --all-features -- -D warnings

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all --all-targets --all-features

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --all --all-targets --all-features
